language: python
python:
  - 3.3
  - 3.4

install: pip install --no-use-wheel -r requirements.txt
script:
  - flake8 --max-complexity 10 .
  - pep257 . --explain

notifications:
  email:
    recipients:
      - PatchIt@noreply.github.com
    on_success: change
    on_failure: change
